[supervisord]
nodaemon=true
loglevel=info

[program:server]
command=/app/entrypoint_server.sh
autostart=true
autorestart=true
environment=PYTHONUNBUFFERED="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scheduler]
command=/app/entrypoint_scheduler.sh
autostart=true
autorestart=true
environment=PYTHONUNBUFFERED="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

